from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.io.serialization import write_bytes_atomic, write_text_atomic  # noqa: E402


SOURCE = ROOT / "output" / "design_preview" / "newsletter_preview.html"
TARGET_DIR = ROOT / "public_preview"


def main() -> None:
    if not SOURCE.exists():
        raise FileNotFoundError(f"Preview HTML does not exist: {SOURCE}")
    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    write_bytes_atomic(TARGET_DIR / "index.html", SOURCE.read_bytes())
    chart_source = SOURCE.parent / "chart_of_the_week.png"
    if chart_source.exists():
        write_bytes_atomic(TARGET_DIR / "chart_of_the_week.png", chart_source.read_bytes())
    write_text_atomic(TARGET_DIR / ".nojekyll", "")
    write_text_atomic(
        TARGET_DIR / "README.txt",
        "Static Weekly Market Brief preview generated by GitHub Actions.\n"
        "This artifact intentionally contains rendered HTML only, not .env, raw keys, audit logs, or JSON outputs.\n",
    )
    print(f"GitHub Pages preview prepared at {TARGET_DIR}")


if __name__ == "__main__":
    main()
