from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "output" / "design_preview" / "newsletter_preview.html"
TARGET_DIR = ROOT / "public_preview"


def main() -> None:
    if not SOURCE.exists():
        raise FileNotFoundError(f"Preview HTML does not exist: {SOURCE}")
    if TARGET_DIR.exists():
        shutil.rmtree(TARGET_DIR)
    TARGET_DIR.mkdir(parents=True)
    shutil.copy2(SOURCE, TARGET_DIR / "index.html")
    chart_source = SOURCE.parent / "chart_of_the_week.png"
    if chart_source.exists():
        shutil.copy2(chart_source, TARGET_DIR / "chart_of_the_week.png")
    (TARGET_DIR / ".nojekyll").write_text("", encoding="utf-8")
    (TARGET_DIR / "README.txt").write_text(
        "Static Weekly Market Brief preview generated by GitHub Actions.\n"
        "This artifact intentionally contains rendered HTML only, not .env, raw keys, audit logs, or JSON outputs.\n",
        encoding="utf-8",
    )
    print(f"GitHub Pages preview prepared at {TARGET_DIR}")


if __name__ == "__main__":
    main()
